version: '3.8'
services:
  social_network_db:
    image: postgres:14.1-alpine
    container_name: social_network_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=social_network_db
    ports:
      - '5430:5432'