name: Social-Network-CI

on:
  pull_request:
    branches:
      - dev

jobs:
  compile-social-network:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn -B compile
  test-social-network:
    needs:
      - compile-social-network
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run tests with Maven
        run: mvn -B test